//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyExchange.Client.ExchangeServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeRateDto", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
    [System.SerializableAttribute()]
    public partial class ExchangeRateDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode {
            get {
                return this.CurrencyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyCodeField, value) != true)) {
                    this.CurrencyCodeField = value;
                    this.RaisePropertyChanged("CurrencyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName {
            get {
                return this.CurrencyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyNameField, value) != true)) {
                    this.CurrencyNameField = value;
                    this.RaisePropertyChanged("CurrencyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mid {
            get {
                return this.MidField;
            }
            set {
                if ((this.MidField.Equals(value) != true)) {
                    this.MidField = value;
                    this.RaisePropertyChanged("Mid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
    [System.SerializableAttribute()]
    public partial class ExchangeServiceFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeRequestDto", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
    [System.SerializableAttribute()]
    public partial class ExchangeRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToCurrencyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCurrency {
            get {
                return this.FromCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.FromCurrencyField, value) != true)) {
                    this.FromCurrencyField = value;
                    this.RaisePropertyChanged("FromCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCurrency {
            get {
                return this.ToCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCurrencyField, value) != true)) {
                    this.ToCurrencyField = value;
                    this.RaisePropertyChanged("ToCurrency");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExchangeResultDto", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
    [System.SerializableAttribute()]
    public partial class ExchangeResultDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CurrencyExchange.Client.ExchangeServiceReference.RateInfoDto[] RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CurrencyExchange.Client.ExchangeServiceReference.RateInfoDto[] Rate {
            get {
                return this.RateField;
            }
            set {
                if ((object.ReferenceEquals(this.RateField, value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateInfoDto", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
    [System.SerializableAttribute()]
    public partial class RateInfoDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency {
            get {
                return this.CurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyField, value) != true)) {
                    this.CurrencyField = value;
                    this.RaisePropertyChanged("Currency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Mid {
            get {
                return this.MidField;
            }
            set {
                if ((this.MidField.Equals(value) != true)) {
                    this.MidField = value;
                    this.RaisePropertyChanged("Mid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExchangeServiceReference.IExchangeService")]
    public interface IExchangeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetExchangeRates", ReplyAction="http://tempuri.org/IExchangeService/GetExchangeRatesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CurrencyExchange.Client.ExchangeServiceReference.ExchangeServiceFault), Action="http://tempuri.org/IExchangeService/GetExchangeRatesExchangeServiceFaultFault", Name="ExchangeServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
        CurrencyExchange.Client.ExchangeServiceReference.ExchangeRateDto[] GetExchangeRates();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetExchangeRates", ReplyAction="http://tempuri.org/IExchangeService/GetExchangeRatesResponse")]
        System.Threading.Tasks.Task<CurrencyExchange.Client.ExchangeServiceReference.ExchangeRateDto[]> GetExchangeRatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetExchangeRate", ReplyAction="http://tempuri.org/IExchangeService/GetExchangeRateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CurrencyExchange.Client.ExchangeServiceReference.ExchangeServiceFault), Action="http://tempuri.org/IExchangeService/GetExchangeRateExchangeServiceFaultFault", Name="ExchangeServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
        double GetExchangeRate(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/GetExchangeRate", ReplyAction="http://tempuri.org/IExchangeService/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/ExchangeCurrency", ReplyAction="http://tempuri.org/IExchangeService/ExchangeCurrencyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CurrencyExchange.Client.ExchangeServiceReference.ExchangeServiceFault), Action="http://tempuri.org/IExchangeService/ExchangeCurrencyExchangeServiceFaultFault", Name="ExchangeServiceFault", Namespace="http://schemas.datacontract.org/2004/07/CurrencyExchange.Service.Models")]
        CurrencyExchange.Client.ExchangeServiceReference.ExchangeResultDto ExchangeCurrency(CurrencyExchange.Client.ExchangeServiceReference.ExchangeRequestDto request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IExchangeService/ExchangeCurrency", ReplyAction="http://tempuri.org/IExchangeService/ExchangeCurrencyResponse")]
        System.Threading.Tasks.Task<CurrencyExchange.Client.ExchangeServiceReference.ExchangeResultDto> ExchangeCurrencyAsync(CurrencyExchange.Client.ExchangeServiceReference.ExchangeRequestDto request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IExchangeServiceChannel : CurrencyExchange.Client.ExchangeServiceReference.IExchangeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExchangeServiceClient : System.ServiceModel.ClientBase<CurrencyExchange.Client.ExchangeServiceReference.IExchangeService>, CurrencyExchange.Client.ExchangeServiceReference.IExchangeService {
        
        public ExchangeServiceClient() {
        }
        
        public ExchangeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExchangeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExchangeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CurrencyExchange.Client.ExchangeServiceReference.ExchangeRateDto[] GetExchangeRates() {
            return base.Channel.GetExchangeRates();
        }
        
        public System.Threading.Tasks.Task<CurrencyExchange.Client.ExchangeServiceReference.ExchangeRateDto[]> GetExchangeRatesAsync() {
            return base.Channel.GetExchangeRatesAsync();
        }
        
        public double GetExchangeRate(string currencyCode) {
            return base.Channel.GetExchangeRate(currencyCode);
        }
        
        public System.Threading.Tasks.Task<double> GetExchangeRateAsync(string currencyCode) {
            return base.Channel.GetExchangeRateAsync(currencyCode);
        }
        
        public CurrencyExchange.Client.ExchangeServiceReference.ExchangeResultDto ExchangeCurrency(CurrencyExchange.Client.ExchangeServiceReference.ExchangeRequestDto request) {
            return base.Channel.ExchangeCurrency(request);
        }
        
        public System.Threading.Tasks.Task<CurrencyExchange.Client.ExchangeServiceReference.ExchangeResultDto> ExchangeCurrencyAsync(CurrencyExchange.Client.ExchangeServiceReference.ExchangeRequestDto request) {
            return base.Channel.ExchangeCurrencyAsync(request);
        }
    }
}
